/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, Category, StoreSettings, SystemLog } from "./types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "p1",
    nameEn: "Atelier Amber Extract Perfume",
    nameBn: "অ্যাটেলিয়ার আম্বার এক্সট্র্যাক্ট পারফিউম",
    category: "Perfume",
    subCategory: "Men Perfume",
    price: 120,
    regularPrice: 150,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "A luxurious scent crafted with base notes of rich amber, aged cedar, and high mountain vetiver, producing an elegant, long-lasting oriental breeze.",
    descriptionBn: "সমৃদ্ধ আম্বার, পরিপক্ক সিডার এবং পাহাড়ি ভেটিভারের বেস নোট দিয়ে তৈরি একটি বিলাসবহুল সুগন্ধি যা একটি চমৎকার দীর্ঘস্থায়ী সুবাস ছড়ায়।",
    inventory: 24,
    isFeatured: true,
    offers: true,
    specificationsEn: ["Top notes: Cardamom, Bergamot", "Heart notes: Vetiver, Jasmine", "Base notes: Amber, Cedarwood, Leather", "Volume: 100ml / 3.4 Fl. Oz"],
    specificationsBn: ["শীর্ষ নোট: এলাচ, বারগামট", "হার্ট নোট: ভেটিভার, জুঁই", "বেস নোট: আম্বার, সিডারউড, চামড়া", "ভলিউম: ১০০ মিলি / ৩.৪ আউন্স"]
  },
  {
    id: "p_perfume_women",
    nameEn: "Rose Oud Elixir de Parfum",
    nameBn: "রোজ আউদ এলিক্সির ডি পারফাম",
    category: "Perfume",
    subCategory: "Women Perfume",
    price: 135,
    regularPrice: 160,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "An exquisite rose-centered feminine perfume rich in organic Bulgarian rose essence, velvet peach, sweet vanilla pods, and soft agarwood.",
    descriptionBn: "অর্গানিক বুলগেরিয়ান গোলাপের নির্যাসে সমৃদ্ধ একটি চমৎকার নারীত্বপূর্ণ পারফিউম, যাতে রয়েছে ভেলভেট পিচ, মিষ্টি ভ্যানিলা এবং মৃদু আগরউডের মনমুগ্ধকর সমন্বয়।",
    inventory: 18,
    isFeatured: true,
    offers: false,
    specificationsEn: ["Top notes: Peach, Litchi", "Heart notes: Bulgarian Rose, Lily", "Base notes: Madagascar Vanilla, White Musk, Oud", "Volume: 80ml / 2.7 Fl. Oz"],
    specificationsBn: ["শীর্ষ নোট: পিচ, লিচি", "হার্ট নোট: বুলগেরিয়ান গোলাপ, লিলি", "বেস নোট: মাদাগাস্কার ভ্যানিলা, কস্তুরী, আউদ", "ভলিউম: ৮০ মিলি"]
  },
  {
    id: "p_perfume_spray",
    nameEn: "Atelier Marine Breeze Body Spray",
    nameBn: "অ্যাটেলিয়ার মেরিন ব্রিজ বডি স্প্রে",
    category: "Perfume",
    subCategory: "Men & Women Body Spray",
    price: 30,
    regularPrice: 45,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "A refreshing, everyday dynamic master body spray for both men and women, featuring cool maritime salt, crushed mint leaves, and ozone chords.",
    descriptionBn: "নারী ও পুরুষ উভয়ের জন্যই একটি অনবদ্য ও সতেজ বডি স্প্রে, যাতে রয়েছে সামুদ্রিক লবণ, পুদিনা পাতা এবং ওজোন নোটের এক অপূর্ব শীতল মিশ্রণ।",
    inventory: 40,
    isFeatured: false,
    offers: true,
    specificationsEn: ["Longevity: 8 Hours active", "Notes: Sea Salt, Spearmint, Cedar", "Skin Type: Sensitive safe tested", "Volume: 150ml / 5.1 Fl. Oz"],
    specificationsBn: ["স্থায়িত্ব: ৮ ঘন্টা সক্রিয়", "নোট: সামুদ্রিক লবণ, পুদিনা, সিডার", "ত্বকের ধরন: সংবেদনশীল ত্বকে ব্যবহার উপযোগী", "ভলিউম: ১৫০ মিলি"]
  },
  {
    id: "p_perfume_attar",
    nameEn: "Dehn Al Oud Royale Concentrated Attar",
    nameBn: "দেহন আল আউদ রয়্যাল কনসেন্ট্রেটেড আতর",
    category: "Perfume",
    subCategory: "Attar",
    price: 65,
    regularPrice: 80,
    image: "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "Traditional pure, alcohol-free concentrated oil attar woven from rare Cambodian Oud wood, warm spices, and mystical musk.",
    descriptionBn: "কম্বোডিয়ান আউদ কাঠ, গরম মশলা এবং কস্তুরীর সুবাসে সমৃদ্ধ প্রথাগত খাঁটি, অ্যালকোহল মুক্ত ঘন সুগন্ধযুক্ত আতর।" ,
    inventory: 15,
    isFeatured: true,
    offers: true,
    specificationsEn: ["Concentration: 100% Pure Attar Oil", "Alcohol: Free (Halal Friendly)", "Drip Application: Glass applicator rod", "Volume: 12ml / 0.4 Fl. Oz"],
    specificationsBn: ["ঘনত্ব: ১০০% খাঁটি আতরের তেল", "অ্যালকোহল: সম্পূর্ণ মুক্ত ও হালাল", "প্রয়োগ: কাঁচের রড অ্যাপ্লিকেটর", "ভলিউম: ১২ মিলি"]
  },
  {
    id: "p2",
    nameEn: "Heavyweight Linen Atelier Shirt",
    nameBn: "হেভিওয়েট লিনেন অ্যাটেলিয়ার শার্ট",
    category: "Clothing",
    price: 85,
    regularPrice: 110,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "Tailored from 100% organic heavyweight linen with a soft wash. Features structured shoulder lines, a relaxed camp collar, and custom horn buttons.",
    descriptionBn: "১০০% জৈব হেভিওয়েট লিনেন থেকে নরম ওয়াশ সহ তৈরি। এতে রয়েছে কাঠামোগত শোল্ডার লাইন, আরামদায়ক ক্যাম্প কলার এবং কাস্টম হর্ন বোতাম।",
    inventory: 35,
    isFeatured: true,
    specificationsEn: ["100% Certified Organic Belgian Linen", "Pre-washed for optimal drape", "Relaxed unisex silhouette", "Corozo seed custom buttons"],
    specificationsBn: ["১০০% প্রত্যয়িত জৈব বেলজিয়ান লিনেন", "উপযুক্ত ফিটিংয়ের জন্য প্রি-ওয়াশড", "রিল্যাক্সড ইউনিসেক্স ডিজাইন", "কোরোজো সিড কাস্টম বোতাম"]
  },
  {
    id: "p3",
    nameEn: "Chrono Minimaliste IV Slate Watch",
    nameBn: "ক্রোনো মিনিমালিস্ট ৪ স্লেট ঘড়ি",
    category: "Watches",
    price: 240,
    regularPrice: 320,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?auto=format&fit=crop&q=80&w=600"
    ],
    descriptionEn: "A masterpiece of modern horology. Features a brushed grade-5 titanium case, a Swiss quartz caliber, scratch-resistant sapphire crystal, and matte slate dial.",
    descriptionBn: "আধুনিক ঘড়ি শিল্পের একটি অনবদ্য সৃষ্টি। ব্রাশড গ্রেড-৫ টাইটানিয়াম কেস, সুইস কোয়ার্টজ ক্যালিবার, স্ক্র্যাচ-প্রতিরোধী স্যাফায়ার ক্রিস্টাল এবং ম্যাট স্লেট ডায়াল বিশিষ্ট।",
    inventory: 15,
    isFeatured: true,
    offers: true,
    specificationsEn: ["Case size: 38mm", "Thickness: 7.2mm", "Strap: Brushed titanium links", "Water resistance: 5 ATM (50m)"],
    specificationsBn: ["কেস আকার: ৩৮ মিলিমিটার", "পুরুত্ব: ৭.২ মিলিমিটার", "স্ট্র্যাপ: ব্রাশড টাইটানিয়াম লিংক", "ওয়াটার রেজিস্ট্যান্স: ৫ এটিএম"]
  },
  {
    id: "p4",
    nameEn: "Textured Ceramic Sculpture Vase",
    nameBn: "টেক্সচার্ড সিরামিক স্কাল্পচার ফুলদানি",
    category: "Home Decoration",
    price: 65,
    image: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Hand-thrown in Denmark with heavy iron-rich stoneware. The sandblasted mineral finish provides structural depth that adapts beautifully to shifting natural studio light.",
    descriptionBn: "ডেনমার্কে তৈরি হেভি আয়রন-রিচ স্টোনওয়্যার ফুলদানি। স্যান্ডব্লাস্টেড খনিজ ফিনিশ একটি কাঠামোগত গভীরতা প্রদান করে যা স্টুডিওর আলোতে চমৎকার দেখায়।",
    inventory: 40,
    specificationsEn: ["Material: Stoneware clay", "Finish: Sandblasted cream mineral", "Height: 28cm / 11 in", "Weight: 1.8 kg"],
    specificationsBn: ["উপাদান: স্টোনওয়্যার কাদা", "ফিনিশ: স্যান্ডব্লাস্টেড ক্রিম মিনারেল", "উচ্চতা: ২৮ সেমি", "ওজন: ১.৮ কেজি"]
  },
  {
    id: "p5",
    nameEn: "Organic Bamboo Muslin Swaddle Set",
    nameBn: "অর্গানিক ব্যাম্বু মসলিন সোয়াডেল সেট",
    category: "Baby Care",
    price: 45,
    regularPrice: 60,
    image: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Crafted from unbleached organic bamboo and medical-grade long-staple cotton, establishing a breathable, cloud-like softness safe for newborn delicate skin.",
    descriptionBn: "অশোধিত অর্গানিক বাঁশ এবং দীর্ঘআঁশের তুলা থেকে তৈরি, নবজাতকের কোমল ত্বকের জন্য একটি নিঃসশ্বাসযোগ্য ও ক্লাউড-লাইভ কোমলতা নিশ্চিত করে।",
    inventory: 50,
    offers: true,
    specificationsEn: ["Set context: 3 Swaddles", "Composition: 70% Organic Bamboo, 30% Cotton", "Size: 120 x 120 cm / 47 x 47 in", "Dyeing: Certified non-toxic vegetable inks"],
    specificationsBn: ["সেট সামগ্রী: ৩টি সোয়াডেল", "উপাদান: ৭০% অর্গানিক বাঁশ, ৩০% তুলা", "আকার: ১২০ x ১২০ সেমি", "রঞ্জন: প্রত্যয়িত অ-বিষাক্ত উদ্ভিজ্জ কালি"]
  },
  {
    id: "p6",
    nameEn: "Lossless Studio Monitor Speaker",
    nameBn: "লসলেস স্টুডিও মনিটর স্পিকার",
    category: "Electronics",
    price: 499,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Active near-field monitor inside a handcrafted solid American walnut cabinet. Features bespoke carbon fiber drivers and ultra-clean Class-D amplification.",
    descriptionBn: "আমেরিকান আখরোট কাঠের কেবিনেটে তৈরি অ্যাক্টিভ নিয়ার-ফিল্ড মনিটর। কাস্টম কার্বন ফাইবার ড্রাইভার এবং আল্ট্রা-ক্লিন ক্লাস-ডি অ্যামপ্লিফিকেশনের সমন্বয়।",
    inventory: 8,
    isFeatured: true,
    specificationsEn: ["Frequency Range: 45Hz - 22kHz", "Amplifier Power: 100W RMS per unit", "Inputs: Balanced XLR, Optical, WiFi Streaming", "Dimensions: 32 x 18 x 22 cm"],
    specificationsBn: ["ফ্রিকোয়েন্সি পরিসীমা: ৪৫Hz - ২২kHz", "অ্যামপ্লিফায়ার পাওয়ার: ১০০W আরএমএস", "ইনপুট: সুষম XLR, অপটিক্যাল, ওয়াইফাই", "মাত্রা: ৩২ x ১৮ x ২২ সেমি"]
  },
  {
    id: "p7",
    nameEn: "Artisanal Single-Origin Darjeeling Tea",
    nameBn: "আর্টিসানাল সিঙ্গেল-অরিজিন দার্জিলিং চা",
    category: "Food & Beverage",
    subCategory: "Drinks",
    price: 35,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Ultra-premium first-flush hand-plucked whole leaves from elevated organic high gardens. Presents rich Muscatel notes and a refined floral finish.",
    descriptionBn: "উঁচু পাহাড়ের অর্গানিক বাগান থেকে সংগ্রহ করা আল্ট্রা-প্রিমিয়াম ফার্স্ট-ফ্লাশ সম্পূর্ণ চা পাতা। এতে রয়েছে চমৎকার মাসকাটেল ফ্লেভার এবং একটি রিফাইন করা ফ্লোরাল ফিনিশ।",
    inventory: 60,
    specificationsEn: ["Flush: First Flush Spring", "Origin: Kurseong Hills, Darjeeling", "Net weight: 150g Tin Case", "Harvest Method: Hand-plucked, custom line dried"],
    specificationsBn: ["ফ্লাশ: প্রথম ফ্লাশ বসন্ত", "উত্স: কার্সিওং হিলস, দার্জিলিং", "নেট ওজন: ১৫০ গ্রাম টিনের কেস", "সংগ্রহ পদ্ধতি: হস্ত-নির্বাচিত, প্রথাগত উপায়ে শুষ্ক"]
  },
  {
    id: "p8",
    nameEn: "Bengal Unfiltered Wild Forest Honey",
    nameBn: "সুন্দরবনের খাঁটি বুনো ফুলের মধু",
    category: "Food & Beverage",
    subCategory: "Honey",
    price: 40,
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Harvested sustainably from deep wild forests of the deep delta. Completely unfiltered and unpasteurized, retaining raw digestive enzymes, minerals and deep pollen undertones.",
    descriptionBn: "সুন্দরবনের গভীর বম্যাঞ্চল থেকে টেকসই উপায়ে সংগৃহীত। সম্পূর্ণ অপরিশোধিত এবং অপাস্তুরিত, যা প্রাকৃতিক এনজাইম, খনিজ উপাদান এবং পোলেন উপাদানকে ধরে রাখে।",
    inventory: 45,
    offers: true,
    specificationsEn: ["Purity: 100% Raw Unfiltered Honey", "Nectar Type: Sundarbans Wild Mangrove flowers", "Weight: 450g Premium Glass Jar", "Certification: Organic Delta Harvest Standard"],
    specificationsBn: ["বিশুদ্ধতা: ১০০% প্রাকৃতিক কাঁচা অপরিশোধিত মধু", "নেক্টার প্রকার: সুন্দরবনের বুনো ম্যানগ্রোভ ফুল", "ওজন: ৪৫০ গ্রাম প্রিমিয়াম কাঁচের জার", "শংসাপত্র: জৈব ডেল্টা স্ট্যান্ডার্ড"]
  },
  {
    id: "p9",
    nameEn: "Minimalist Full Grain Leather Tote",
    nameBn: "মিনিমালিস্ট ফুল গ্রেইন লেদার টোট ব্যাগ",
    category: "Bags",
    price: 180,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "Hand-stitched from full-grain pebbled Tuscan hide with solid brass studs. Includes a raw suede interior with structured laptop partitions and key hook.",
    descriptionBn: "সলিড ব্রাস স্টাড সহ ইতালীয় ফুল-গ্রেইন লেদার ধেকে হাতে সেলাই করা। একটি কাঁচা সোয়েড অভ্যন্তরীণ ল্যাপটপ পার্টিশন এবং কী হুক অন্তর্ভুক্ত।",
    inventory: 12,
    isFeatured: true,
    specificationsEn: ["Leather grade: Full Grain Pebbled", "Lining: Unlined raw suede reverse", "Fits up to: 15in Macbook Pro", "Drop height: 25cm / 9.8 in"],
    specificationsBn: ["লেদার গ্রেড: ফুল গ্রেইন পেবেলড", "আস্তরণ: অপরিশোধিত কাঁচা চামড়ার সোয়েড", "উপযোগী: ১৫ ইঞ্চি ল্যাপটপ", "উচ্চতা ড্রপ: ২৫ সেমি"]
  },
  {
    id: "p10",
    nameEn: "Geometric Maple Block Atelier Toy",
    nameBn: "জ্যামিতিক ম্যাপেল কাঠের ব্লক খেলনা",
    category: "Toys",
    price: 55,
    image: "https://images.unsplash.com/photo-1515488042361-404e9250afef?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "A set of 12 solid curly maple architect blocks finished with organic soy wax and non-toxic food-safe mineral tints to encourage structural design thinking.",
    descriptionBn: "১২টি সলিড কোঁকড়ানো ম্যাপেল আর্কিটেক্ট ব্লকের একটি সেট, যা কাস্টম আর্কিটেক্ট ডিজাইনে অনুপ্রাণিত করতে অর্গানিক সয় মোম এবং অ-বিষাক্ত মিনারেল কালার দিয়ে নিখুঁত ফিনিশ করা।",
    inventory: 20,
    specificationsEn: ["Set context: 12 Solid wooden shapes", "Material: Sustainably managed North American Maple", "Coating: Cold-pressed organic wax with ochre tints", "Pack: Felt travel bag in organic merino"],
    specificationsBn: ["সেট সামগ্রী: ১২টি সলিড আকৃতি", "উপাদান: টেকসই উত্তর আমেরিকান ম্যাপেল কাঠ", "প্রলেপ: কোল্ড-প্রেসড জৈব মোম এবং খনিজ পেইন্ট", "প্যাকিং: অর্গানিক মেরিনো উল ফেল্ট ব্যাগ"]
  },
  {
    id: "p11",
    nameEn: "Atelier Mineral Glow Seed Facial Oil",
    nameBn: "অ্যাটেলিয়ার মিনারেল গ্লো বীজ ফেসিয়াল অয়েল",
    category: "Cosmetics",
    price: 75,
    image: "https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&q=80&w=600",
    descriptionEn: "An ultra-thin, dry elixir of cold-pressed pomegranate seed oil, organic squalane and wild rose absolute for intense cellular skin hydration and luminous gloss.",
    descriptionBn: "তীব্র সেলুলার হাইড্রেশন এবং উজ্জ্বল চকচকে ত্বকের জন্য কোল্ড-প্রেসড ডালিমের বীজ তেল, অর্গানিক স্কোয়ালেন এবং বুনো গোলাপের অতি-পাতলা ড্রাই অলৌকিক মিশ্রণ।",
    inventory: 28,
    isFeatured: true,
    offers: true,
    specificationsEn: ["Core actives: 100% Organic Pomegranate Seed, Squalane", "Texture: Micro-filtered ultra-light dry oil", "Scent: Rose absolute & white vetiver", "Volume: 50ml / 1.7 Fl. Oz"],
    specificationsBn: ["মূল উপাদান: ১০০% অর্গানিক ডালিম বীজ, স্কোয়ালেন", "টেক্সচার: মাইক্রো-ফিল্টার করা আল্ট্রা-লাইট ড্রাই অয়েল", "সুগন্ধ: রোজ এবসোলিউট এবং হোয়াইট ভেটিভার", "সাউন্ডিং ভলিউম: ৫০ মিলি / ১.৭ আউন্স"]
  }
];

export const INITIAL_SETTINGS: StoreSettings = {
  buyMoreSaveMoreEnabled: true,
  tier2Qty: 2,
  tier2Discount: 5,
  tier3Qty: 3,
  tier3Discount: 15,
  tier4Qty: 5,
  tier4Discount: 20,
  bulkPriceEnabled: true,
  bulkMinQty: 10,
  bulkFlatPrice: 450,
  bulkAdvancePercent: 30,
  showAnnouncement: true,
  announcementEn: "STUDIO SUMMER PREVIEW: COMPLIMENTARY EXPEDITED SHIPPING & ACTIVE BUNDLE PRICING",
  announcementBn: "স্টুডিও সামার প্রিভিউ: কমপ্লিমেন্টারি এক্সপ্রেস শিপিং এবং সক্রিয় বান্ডেল ডিসকাউন্ট",
  passphraseHash: "riemart2026",
  storeSignatureText: "Riemart Atelier - Team Lead Signature",
  storeSignatureImage: "",
  facebookPageUrl: "https://www.facebook.com/riemart.bd",
  facebookMessengerUsername: "riemart.bd",
  publicStoreDomain: "https://riemart.com"
};

export const INITIAL_LOGS: SystemLog[] = [
  {
    id: "log-1",
    timestamp: "2026-05-31T12:00:00Z",
    type: "info",
    messageEn: "Atelier system loaded successfully in development container",
    messageBn: "ডেভেলপমেন্ট কন্টেইনারে অ্যাটেলিয়ার সিস্টেম সফলভাবে লোড হয়েছে",
    operator: "Nginx Ingress Proxy"
  },
  {
    id: "log-2",
    timestamp: "2026-05-31T12:05:00Z",
    type: "security",
    messageEn: "Admin Security Portal armed with SHA-256 local token challenge",
    messageBn: "SHA-256 লোকাল টোকেন চ্যালেঞ্জ সহ অ্যাডমিন সিকিউরিটি পোর্টাল সক্রিয় করা হয়েছে",
    operator: "Kernel Guard"
  },
  {
    id: "log-3",
    timestamp: "2026-05-31T14:15:00Z",
    type: "success",
    messageEn: "Inventory synchronization completed for 10 core categories",
    messageBn: "১০টি মূল ক্যাটাগরির জন্য পণ্য তালিকা সিনক্রোনাইজেশন সম্পন্ন হয়েছে",
    operator: "Catalog Sync Agent"
  },
  {
    id: "log-4",
    timestamp: "2026-05-31T15:00:00Z",
    type: "info",
    messageEn: "Gemini server-side proxy initial handshake active",
    messageBn: "জেমিনি সার্ভার-সাইড প্রক্সি প্রাথমিক হ্যান্ডশেক ক্রিয়াকলাপ সম্পন্ন",
    operator: "AI Core Proxy"
  }
];

export const CATEGORIES: Category[] = [
  "Food & Beverage",
  "Perfume",
  "Clothing",
  "Watches",
  "Home Decoration",
  "Baby Care",
  "Electronics",
  "Bags",
  "Toys",
  "Cosmetics"
];

export const CATEGORY_TRANSLATIONS: Record<Category, { en: string; bn: string }> = {
  Clothing: { en: "Clothing", bn: "পোশাক" },
  Perfume: { en: "Perfume", bn: "পারফিউম" },
  Watches: { en: "Watches", bn: "ঘড়ি" },
  "Home Decoration": { en: "Home Decoration", bn: "গৃহসজ্জা" },
  "Baby Care": { en: "Baby Care", bn: "শিশুর যত্ন" },
  Electronics: { en: "Electronics", bn: "ইলেকট্রনিক্স" },
  "Food & Beverage": { en: "Food & Beverage", bn: "খাদ্য ও পানীয়" },
  Bags: { en: "Bags", bn: "ব্যাগ" },
  Toys: { en: "Toys", bn: "খেলনা" },
  Cosmetics: { en: "Cosmetics", bn: "প্রসাধন সামগ্রী" }
};

export const DICTIONARY = {
  en: {
    brandName: "RIEMART.com",
    brandSubtitle: "STUDIO ATELIER",
    domain: "RIEMART.COM",
    searchPlaceholder: "Search unique studio pieces...",
    categories: "Categories",
    allProducts: "All Products",
    featured: "Featured Collection",
    offers: "Offers & Promotions",
    buyMoreSaveMore: "Buy More, Save More",
    quantity: "Quantity",
    inventoryState: "In Stock",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    specifications: "Technical Specifications",
    productDetails: "Product Narrative",
    cartTitle: "Your Atelier Cart",
    cartEmpty: "No items in draft cart.",
    wishlistTitle: "Your Atelier Wishlist",
    wishlistEmpty: "No saved items in wishlist.",
    wishlistButton: "Wishlist",
    addToWishlist: "Save to Wishlist",
    removeFromWishlist: "Remove from Wishlist",
    checkout: "Proceed to Checkout",
    orderSummary: "Order Abstract",
    subtotal: "Subtotal",
    discount: "Bundle Discount",
    deliveryCost: "Delivery Charge",
    free: "Complimentary",
    total: "Total Cost",
    languageLabel: "Language",
    english: "English",
    bengali: "বাংলা",
    adminPortal: "Admin Security Portal",
    controlRoom: "Atelier Control Room",
    adminPassphrase: "Enter Studio Security Passphrase",
    adminUnlock: "Grant Security Access",
    adminIncorrect: "Incorrect administrative credentials.",
    adminPlaceholder: "••••••••",
    adminStatus: "System Authorization: SECURED",
    adminLogout: "Seal Sessions",
    statistics: "Atelier Metrics",
    totalSales: "Accumulated Sales",
    totalOrders: "Total Direct Orders",
    activeItems: "Active Catalog Items",
    activeStaffName: "Active Operator",
    systemAuditLog: "System Audit Logs",
    productManagement: "Catalog Matrix Editor",
    createNewProduct: "Deploy New Studio Artifact",
    editProduct: "Update Artifact Specifications",
    deleteAlert: "Are you sure you want to retire this product from catalog?",
    nameEn: "Name (English)",
    nameBn: "Name (Bengali)",
    descrEn: "Narrative (English)",
    descrBn: "Narrative (Bengali)",
    priceNum: "Price (USD, converts to ৳ BDT)",
    stockNum: "Initial Inventory",
    imageUrl: "Image URL",
    saveChange: "Upload Specs",
    cancel: "Cancel",
    geminiAssistant: "Gemini Creative Copywriter",
    geminiPrompt: "Specify product criteria (e.g. Luxurious Rose, Oud, Gold Flakes) for automated description generation...",
    geminiGenerate: "Ask Gemini to Compose Description",
    geminiStatus: "Consulting server-side model...",
    activePromotions: "Active Promotional Matrices",
    bundleRates: "Active Bundle Tiers",
    tierEnabled: "Tier Discount Logic Enabled",
    tierDetails: "Buy {qty} items and instantly save {disc}% off the active stack",
    announcementControl: "Global Banner Announcement Control",
    bannerEn: "Banner Text (English)",
    bannerBn: "Banner Text (Bengali)",
    bannerShow: "Render Announcement Ribbon",
    saveSettings: "Push Live Settings",
    checkoutSuccess: "Atelier Order Dispatched! Order reference: {id}",
    checkoutFormHeader: "Carriage Particulars",
    customerName: "Buyer's Full Name",
    customerPhone: "Secure Active Mobile Phone",
    customerAddress: "Delivery Address & Carriage Route",
    cancelOrder: "Dismiss Cart",
    placeOrder: "Dispatch Atelier Order",
    ordersList: "Active Dispatch Queue",
    orderId: "Order Ref",
    buyer: "Buyer",
    status: "Status",
    date: "Dispatch Timestamp",
    action: "Operation",
    totalUnits: "Total Units Purchased",
    notifyMeBtn: "Notify me on price drop",
    notifyMeTitle: "Subscribe to Price Drop Alerts",
    notifyMeDesc: "Enter your email or phone number below. We will ping you instantly when this product gets discounted.",
    notifyPlaceholder: "Email or phone number...",
    notifySubscribe: "Activate Alert",
    notifySuccessMsg: "✓ Set up! We'll notify you of any price decrease on this item.",
    notifyAlreadySubscribed: "✓ You have already subscribed on this item.",
    notifyErrorMsg: "Please enter a valid email address or phone number.",
    subscribersTab: "Price Alert Subscribers",
    subscribing: "Subscribed Emails/Phones"
  },
  bn: {
    brandName: "রিয়ামার্ট.কম",
    brandSubtitle: "স্টুডিও অ্যাটেলিয়ার",
    domain: "RIEMART.COM",
    searchPlaceholder: "স্টুডিওর অনন্য পণ্য খুঁজুন...",
    categories: "ক্যাটাগরি সমূহ",
    allProducts: "সব পণ্যসম্ভার",
    featured: "বিশেষ আকর্ষণ",
    offers: "অফার এবং প্রমোশন",
    buyMoreSaveMore: "বেশি কিনুন, বেশি বাঁচুন",
    quantity: "পরিমাণ",
    inventoryState: "স্টক এ আছে",
    addToCart: "কার্টে যুক্ত করুন",
    buyNow: "সরাসরি কিনুন",
    specifications: "প্রযুক্তিগত বিবরণ",
    productDetails: "পণ্যের বিস্তারিত তথ্য",
    cartTitle: "আপনার শপিং কার্ট",
    cartEmpty: "কার্ট সম্পূর্ণ খালি।",
    wishlistTitle: "আপনার উইশলিস্ট",
    wishlistEmpty: "উইশলিস্টে কোনো পণ্য রাখা হয়নি।",
    wishlistButton: "উইশলিস্ট",
    addToWishlist: "উইশলিস্টে রাখুন",
    removeFromWishlist: "উইশলিস্ট থেকে সরান",
    checkout: "চেকআউট সম্পূর্ণ করুন",
    orderSummary: "অর্ডারের সারসংক্ষেপ",
    subtotal: "উপমোট",
    discount: "বান্ডেল ডিসকাউন্ট",
    deliveryCost: "ডেলিভারি চার্জ",
    free: "ফ্রি (কমপ্লিমেন্টারি)",
    total: "সর্বমোট খরচ",
    languageLabel: "ভাষা",
    english: "English",
    bengali: "বাংলা",
    adminPortal: "অ্যাডমিন সিকিউরিটি পোর্টাল",
    controlRoom: "আই ক্যাটেলিয়ার কন্ট্রোল রুম",
    adminPassphrase: "স্টুডিও সিকিউরিটি পাসফ্রেজ লিখুন",
    adminUnlock: "সিকিউরিটি অ্যাক্সেস অনুমোদন করুন",
    adminIncorrect: "ভুল প্রশাসনিক প্রমাণপত্রাদ।",
    adminPlaceholder: "••••••••",
    adminStatus: "সিস্টেম অনুমোদন: সুরক্ষিত",
    adminLogout: "অ্যাডমিন সেশন বন্ধ করুন",
    statistics: "স্টুডিওর সামগ্রিক পরিসংখ্যান",
    totalSales: "সঞ্চিত মোট বিক্রি",
    totalOrders: "মোট অর্ডারের সংখ্যা",
    activeItems: "সক্রিয় ক্যাটালগ আইটেম",
    activeStaffName: "সক্রিয় অপারেটর",
    systemAuditLog: "সিস্টেম অডিট লগ",
    productManagement: "ক্যাটালগ পণ্য সম্পাদক",
    createNewProduct: "নতুন পণ্য ক্যাটালগে যুক্ত করুন",
    editProduct: "পণ্য বিবরণ পরিবর্তন করুন",
    deleteAlert: "আপনি কি নিশ্চিতভাবে এই পণ্যটি ক্যাটালগ থেকে বাদ দিতে চান?",
    nameEn: "নাম (ইংরেজি)",
    nameBn: "নাম (বাংলা)",
    descrEn: "বিবরণ (ইংরেজি)",
    descrBn: "বিবরণ (বাংলা)",
    priceNum: "মূল্য (USD, যা ৳ BDT-তে রুপান্তর হবে)",
    stockNum: "প্রাথমিক স্টক পরিমাণ",
    imageUrl: "ছবির URL লিঙ্ক",
    saveChange: "পরিবর্তন সংরক্ষণ করুন",
    cancel: "বাতিল করুন",
    geminiAssistant: "জেমিনি ক্রিয়েটিভ কপিরাইটার",
    geminiPrompt: "পণ্যের মূল মানদণ্ড বা কীওয়ার্ড উল্লেখ করুন (যেমন: বিলাসবহুল পারফিউম, কাঠ কয়লা এবং গোলাপের সুবাস) স্বয়ংক্রিয় বিবরণ তৈরির জন্য...",
    geminiGenerate: "জেমিনি দিয়ে পণ্যের বিবরণ লিখুন",
    geminiStatus: "সার্ভার-সাইড এআই মডেলের সাহায্য নেওয়া হচ্ছে...",
    activePromotions: "সক্রিয় প্রমোশনাল অফারসমূহ",
    bundleRates: "সক্রিয় বান্ডেল ডিসকাউন্ট স্ল্যাব",
    tierEnabled: "বান্ডেল ডিসকাউন্ট লজিক সক্রিয় আছে",
    tierDetails: "একসাথে {qty} টি বা তার বেশি কিনলেই মূল্যের ওপর সরাসরি {disc}% ডিসকাউন্ট",
    announcementControl: "গ্লোবাল ব্যানার অ্যানাউন্সমেন্ট কন্ট্রোল",
    bannerEn: "ব্যানার টেক্সট (ইংরেজি)",
    bannerBn: "ব্যানার টেক্সট (বাংলা)",
    bannerShow: "ঘোষণাপত্র রিবন প্রদর্শন করুন",
    saveSettings: "লাইভ কনফিগারেশন আপডেট করুন",
    checkoutSuccess: "অর্ডার সফলভাবে সিস্টেম দ্বারা গৃহীত হয়েছে! অর্ডার নম্বর: {id}",
    checkoutFormHeader: "ডেলিভারি বিবরণ পূরণ করুন",
    customerName: "ক্রেতার পুরো নাম",
    customerPhone: "যোগাযোগের সচল মোবাইল নম্বর",
    customerAddress: "ডেলিভারি ঠিকানা ও রুট ম্যাপ",
    cancelOrder: "কার্ট বাতিল করুন",
    placeOrder: "অর্ডার নিশ্চিত করুন",
    ordersList: "সক্রিয় বিতরণ সারি",
    orderId: "অর্ডার আইডি",
    buyer: "ক্রেতা",
    status: "অবস্থা",
    date: "অর্ডারের সময়কাল",
    action: "অ্যাকশন",
    totalUnits: "মোট ক্রয়ের পরিমাণ",
    notifyMeBtn: "প্রাইস ড্রপ অ্যালার্ট পান",
    notifyMeTitle: "প্রাইস ড্রপ অ্যালার্ট সাবস্ক্রিপশন",
    notifyMeDesc: "আপনার ইমেল বা মোবাইল নম্বর দিন। এই পণ্যে ডিসকাউন্ট দেওয়া হলে আপনাকে তাৎক্ষণিক জানানো হবে।",
    notifyPlaceholder: "ইমেইল অথবা মোবাইল নম্বর...",
    notifySubscribe: "অ্যালার্ট সক্রিয় করুন",
    notifySuccessMsg: "✓ সেটআপ সম্পন্ন! মূল্য কমানো হলে আপনাকে বিজ্ঞপ্তি পাঠানো হবে।",
    notifyAlreadySubscribed: "✓ আপনি ইতিমধ্যে এই পণ্যটিতে সাবস্ক্রাইব করেছেন।",
    notifyErrorMsg: "অনুগ্রহ করে একটি সঠিক ইমেল বা মোবাইল নম্বর দিন।",
    subscribersTab: "মূল্য হ্রাস গ্রাহক তালিকা",
    subscribing: "সাবস্ক্রাইবড ইমেইল/ফোন"
  }
};
